DROP TABLE IF EXISTS REMINDER;
CREATE TABLE REMINDER
(
    ID BIGSERIAL PRIMARY KEY,
    TEXT VARCHAR(50) NOT NULL,
    CHATID BIGSERIAL NOT NULL,
    RUNDATE TIMESTAMP
);
DROP TABLE IF EXISTS TGUSER;
CREATE TABLE TGUSER
(
    ID BIGSERIAL PRIMARY KEY,
    TIMEZONE VARCHAR(50) NOT NULL,
    LANGUAGE VARCHAR(50) NOT NULL
);